name: Dev CronJob Deployment Workflow

on:  # only run this workflow for dev branches.
  push:
    branches-ignore:
      - main
      - release/nonprod
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  gradle-build:
    name: Gradle Build
    uses: Nordstrom-Internal/APP02944-internal-marketplace/.github/workflows/gradle-build.yml@v7
    secrets: inherit
    with:
      gradle-version: 8

  integration-test:
    name: Integration Test
    needs: gradle-build
    runs-on: linux-nonprod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Integration Tests
        uses: ./.github/integration-test
        with:
          app-id: 'APP09831'
          vault-secrets-string: |-
            nonprod/APP09831-transaction-aggregation-service NONPROD_AURORA_TEST_USERNAME
            nonprod/APP09831-transaction-aggregation-service NONPROD_AURORA_TEST_PASSWORD
            nonprod/APP09831-transaction-aggregation-service AURORA_TEST_DATABASE_NAME

  docker-build:
    needs: [gradle-build, integration-test]
    name: Docker Container Build
    uses: Nordstrom-Internal/APP02944-internal-marketplace/.github/workflows/docker.yml@v7
    secrets: inherit
    with:
      app-name: transaction-aggregation-service
      app-id: APP09831
      app-version: ${{ needs.gradle-build.outputs.build-version }}

  nsk-cronjob-deploy-development-branch:
    needs: docker-build
    name: Deploy to NSK Development Branch
    uses: Nordstrom-Internal/APP02944-internal-marketplace/.github/workflows/nsk-deploy.yml@v7
    secrets: inherit
    with:
      github-job-runs-on: linux-nonprod
      github-job-environment: dev
      deployment-environment: dev
      app-name: 'transaction-aggregation-service'
      app-id: 'APP09831'
      app-version: ${{ needs.docker-build.outputs.app-version }}
      container-image-name: ${{ needs.docker-build.outputs.image-name }}
      container-image-tag: ${{ needs.docker-build.outputs.image-tag }}
      cloud-provider: 'aws'
      cloud-region: 'us-west-2'
      cloud-identifier: "007979315855"
      deployment-target: 'nskapp'
      nsk-cluster: 'nsk-maple-nonprod'
      # CronJob specific configurations
      k8s-includes-service: false
      k8s-workload-type: CronJob
      k8s-cronjob-schedule: "15 11 * * *"  # Every day 3:15 AM PST (11:15 AM UTC)
      k8s-irsa-role-arn: 'arn:aws:iam::007979315855:role/fin-data-integration-k8s-access-role-nonprod'
      k8s-container-restart-policy: Never
      k8s-requests-memory: '500Mi'
      k8s-requests-cpu: '300m'
      k8s-namespace: 'app09831'
      k8s-min-replicas: 1
      k8s-max-replicas: 1
      application-secrets-template: |
        env:NEW_RELIC_LICENSE_KEY = ${vault:nonprod/APP09831-transaction-aggregation-service NEW_RELIC_LICENSE_KEY}
        env:AURORA_POSTGRESQL_DATABASE_ENDPOINT = fin-data-integration-cluster-nonprod.cluster-cxcm0iug0tfr.us-west-2.rds.amazonaws.com
        env:AURORA_DATABASE_NAME = ${vault:nonprod/APP09831-transaction-aggregation-service NONPROD_AURORA_DATABASE_NAME}
        env:AURORA_POSTGRESQL_USERNAME = ${vault:nonprod/APP09831-transaction-aggregation-service NONPROD_AURORA_SERVICE_USERNAME}
        env:AURORA_POSTGRESQL_PASSWORD = ${vault:nonprod/APP09831-transaction-aggregation-service NONPROD_AURORA_SERVICE_PASSWORD}
      # environment variables here
      k8s-env-vars: |
        [
          {"name": "ENV_NAME", "value": "dev"},
          {"name": "SPRING_PROFILES_ACTIVE", "value": "dev"},
          {"name": "APP_ID", "value": "APP09831"},
          {"name": "ABSTRACTION_SERVICE_UPLOAD_BUCKET", "value": "app09831-data-integration-test"}
        ]
